### ISSUE TITLE
Snapshot functionality 

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/fabric-sdk-node#530]
Are there plans for the SDK to support snapshots?
https://hyperledger-fabric.readthedocs.io/en/latest/commands/peersnapshot.html?highlight=snapshot

**Comment by bestbeforetoday** [comment]
Since v2.x, SDK development has focused on business application runtime support (invoking transactions and receiving events) and moved away from administrative operations. So unless contributors from the community deliver this capability as part of an admin-focused SDK component, I don't expect to see SDK support for this capability.
