### ISSUE TITLE
Getting two transaction against a insertion 

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/fabric-sdk-node#580]
> ```
> Hi Team ,
> I am implementing contract events for fabcar using node sdk api.so in fabcar go chaincode createCar function ,i have set event in following way.
> =============
>     ` `   ctx.GetStub().SetEvent("CreateCar", carAsBytes)``
> =============
> and for contract events at node js, i m using listener in following way.
> ===============
> try {
>        listener = async (event) => {
>         const car = JSON.parse(event.payload.toString());
>         const eventTransaction = event.getTransactionEvent();
>         const eventBlock = eventTransaction.getBlockEvent();
>                 };
>         await contract.addContractListener(listener);
>         } catch (eventError) {
>                         console.log('<-- Failed: Setup contract events - ${eventError}');
>         }
> 
>     await contract.submitTransaction('createCar' ,'CAR1112', 'Honda', 'Accord', 'Black', 'Tom' );
> 
> ===============
> But when i invoke createcar function,getting two blocks and two transaction id from contract listener object.
> Response is like below.
> 
> ============================
> --> Start contract event stream to peer in Org1
> event.eventName========= CreateCar
> car =================== {"make":"Honda","model":"Accord","colour":"Black","owner":"Tom"}
> transaction========= 9d9111ff665d4fd870bb6c6042a8da3ca6910660bab9915290063504337b4bff
> transaction status========= VALID
> EventBlock.blocknuber========= 27
> event.eventName========= CreateCar
> car =================== {"make":"Honda","model":"Accord","colour":"Black","owner":"Tom"}
> transaction========= a32eb2a5366862f17708802aa7bb86e2b19208c7d9f6d913c5bc5ac0e0632d01
> transaction status========= VALID
> EventBlock.blocknuber========= 28
> 
> ============================
> Why two blocks are generated for single transaction.let me correct if anything wrong.
> 
> Regards,
> 
> ```
> ```

**Comment by bestbeforetoday** [comment]
I had another look at this today and I think the mystery is solved. I started with a newly created blockchain and performed two runs of my simple sample application (above).

Output of the first application run:
```
Received event: CreateAsset
Payload: {
  ID: 'item-989',
  Color: 'blue',
  Size: '10',
  Owner: 'Sam',
  AppraisedValue: '100'
}
Transaction ID: 6d861709e19fc287b3888e1090416bb999502662b5a9ac1604aa86f172e45b14
Block number: 6
```

Output of the second application run:
```
Received event: CreateAsset
Payload: {
  ID: 'item-989',
  Color: 'blue',
  Size: '10',
  Owner: 'Sam',
  AppraisedValue: '100'
}
Transaction ID: 6d861709e19fc287b3888e1090416bb999502662b5a9ac1604aa86f172e45b14
Block number: 6
Received event: CreateAsset
Payload: {
  ID: 'item-12',
  Color: 'blue',
  Size: '10',
  Owner: 'Sam',
  AppraisedValue: '100'
}
Transaction ID: d55c593e2087d0369f1af64a4d722070b6abaa38140e7d5e1a1435715a940d9f
Block number: 7
```

Notice that the first run outputs a single chaincode event (from block 6) while the second outputs two chaincode events (from blocks 6 and 7). The reason is that, when you don't specify an eventing start position, eventing actually begins from the **last** committed block. I would personally prefer it to start from the **next** committed block (as it does in the new [@hyperledger/fabric-gateway](https://github.com/hyperledger/fabric-gateway) API for Fabric v2.4+), but there were reasons for this behaviour based on the eventing implementation in fabric-common.

If you want to avoid duplicating or missing events on subsequent application runs, you can use a [checkpointer](https://hyperledger.github.io/fabric-sdk-node/release-2.2/module-fabric-network.Checkpointer.html) to persist your current eventing position between application runs.

If I change my client application to attach the event listener like this:
```javascript
await contract.addContractListener(listener, {
    checkpointer: await DefaultCheckpointers.file('checkpoint.json'),
});
```

I get the following output for the first application run:
```
Received event: CreateAsset
Payload: {
  ID: 'item-254',
  Color: 'blue',
  Size: '10',
  Owner: 'Sam',
  AppraisedValue: '100'
}
Transaction ID: 7b50171806b1313dfca87b45ac628a83242c295175da0ff2f4b02e3f14e3c9dd
Block number: 6
```

And only this output for the second application run:
```
Received event: CreateAsset
Payload: {
  ID: 'item-919',
  Color: 'blue',
  Size: '10',
  Owner: 'Sam',
  AppraisedValue: '100'
}
Transaction ID: 95f40f62dfb698701d48377c66abe6bf30cb2ea7b18a879664215cefc88e1064
Block number: 7
```

**Comment by bestbeforetoday** [comment]
Closing under the assumption that this has answered your query. If there is any remaining issue, add a comment and we can reopen it.
