### ISSUE TITLE
Getting newIdentityContext not a function

### ISSUE THREAD

**Issue by khushalkunjir** [hyperledger/fabric-sdk-node#616]
const client = require("fabric-common") // using fabric-common version is 2.2.9  

Getting below error,

(node:16303) UnhandledPromiseRejectionWarning: TypeError: client.newIdentityContext is not a function

**Comment by bestbeforetoday** [comment]
The **fabric-common** package doesn't provide a `newIdentityContext()` function directly. **fabric-common** includes a **Client** class, and `newIdentityContext()` is a method on that class. For example:

```javascript
const { Client } = require('fabric-common');

const client = new Client('myclient');
const context = client.newIdentityContext(user);
```

Instead of using fabric-common directly, I would recommend using the [fabric-network](https://www.npmjs.com/package/fabric-network) package. If you are using (or can use) Fabric v2.4 or later, I would recommend using the newer [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/) instead.
